### ISSUE TITLE
Moving over to PDO for azure sql

### ISSUE THREAD

**Issue by magnusandy** [PhlexPlexico/350Assign2#3]
make sure all the files for azure in the /azure folder
the following pages are done
`
azure-login.php
`
these pages are not complete
`
azure-update.php (this file has 3 seperate database connections, only one is changed over to PDO)
`
`
azure-create.php (2 database connections)
`
`
azure-display.php (1 database connection)
`
`
azure-createAccount.php (2 database connections)
`

**Comment by magnusandy** [comment]
also 
`
deleteContactFunction.php (1 connection)
`

**Comment by knames** [comment]
going to assume this is closed
